Some rework.

diff --git a/templates/certbot_helper.sh.erb b/templates/certbot_helper.sh.erb
--- a/templates/certbot_helper.sh.erb
+++ b/templates/certbot_helper.sh.erb
@@ -4,13 +4,14 @@
 # Le Franzose!
 #
 LE_BIN="<%= scope.lookupvar('::al_letsencrypt::le_binary')%>"
-LE_ARGS="<%= scope.lookupvar('::al_letsencrypt::install::le_args')%>"
+LE_ARGS="--webroot --noninteractive --keep-until-expiring --quiet --agree-tos"
 LE_LOG="<%= scope.lookupvar('::al_letsencrypt::le_logdir')%>/letsencrypt.log"
+LE_EMAIL="<%= scope.lookupvar('::al_letsencrypt::email')%>"
 LE_DOMAIN="$1"
 LE_CRT="<%= scope.lookupvar('::al_letsencrypt::le_dir')%>/${LE_DOMAIN}/cert.pem"
 LE_DOCROOT="/var/www/vhosts/${LE_DOMAIN}"
 LE_DOCROOT_FAILBACK="/var/www/vhosts/<%=@fqdn%>"
-LE_DOCROOT_OVERRIDE=""
+LE_DOCROOT_OVERRIDE="<%= scope.lookupvar('::al_letsencrypt::docroot_override')%>"
 
 #
 # Logging and Error.
@@ -27,18 +28,17 @@ function log {
 }
 
 #
-# Load additional Config
-#
-if [ -e /etc/certbot_helper.conf ] ; then
-  log "Loading additional configuration."
-  source /etc/certbot_helper.conf
-fi
-
-#
 # Sanity Checks
 #
 if [ ! -e ${LE_BIN} ]; then
   error "certbot not found (${LE_BIN})"
+fi
+
+#
+# Must be root.
+#
+if [ $(whoami) != 'root' ]; then
+  error "Must be root."
 fi
 
 #
@@ -74,8 +74,18 @@ if [ -e ${LE_CRT} ]; then
 fi
 
 #
+# Email or unsafe registratrion?
+#
+if [ "${LE_EMAIL}" != "" ] ;
+  EMAIL_ARG="--email ${LE_EMAIL}"
+else
+  EMAIL_ARG="--allow-unsafe-registration"
+fi
+
+
+#
 # Run it.
 #
 log "Starting certbox for ${LE_DOMAIN}."
-${LE_BIN} certonly ${LE_ARGS} --webroot-path ${DOCROOT} -d ${LE_DOMAIN} || error "Unable to request certificate for ${LE_DOMAIN}."
+${LE_BIN} certonly ${LE_ARGS} --webroot-path ${DOCROOT} ${EMAIL_ARG} -d ${LE_DOMAIN} || error "Unable to request certificate for ${LE_DOMAIN}."
 log "Certificate for ${LE_DOMAIN} created successfully."
